require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-i18n
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']