version: "3.7"

volumes:
  db: {}

services:
  db:
    image: postgres:13.5
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
