development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: todoser_development
test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL")  %>
  channel_prefix: Todoser_production
